/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_L = 1;
  /** RegularExpression Id. */
  int T_R = 2;
  /** RegularExpression Id. */
  int T_BOOLEAN = 3;
  /** RegularExpression Id. */
  int T_TRUE = 4;
  /** RegularExpression Id. */
  int T_FALSE = 5;
  /** RegularExpression Id. */
  int T_INTEGER = 6;
  /** RegularExpression Id. */
  int T_DEFINE = 7;
  /** RegularExpression Id. */
  int T_ELSE = 8;
  /** RegularExpression Id. */
  int T_COND = 9;
  /** RegularExpression Id. */
  int T_BINARY = 10;
  /** RegularExpression Id. */
  int T_PLUS = 11;
  /** RegularExpression Id. */
  int T_MINUS = 12;
  /** RegularExpression Id. */
  int T_TIMES = 13;
  /** RegularExpression Id. */
  int T_DIVIDE = 14;
  /** RegularExpression Id. */
  int T_EQUAL = 15;
  /** RegularExpression Id. */
  int T_LTEQ = 16;
  /** RegularExpression Id. */
  int T_LT = 17;
  /** RegularExpression Id. */
  int T_GTEQ = 18;
  /** RegularExpression Id. */
  int T_GT = 19;
  /** RegularExpression Id. */
  int T_VARIABLE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "<T_BOOLEAN>",
    "\"#t\"",
    "\"#f\"",
    "<T_INTEGER>",
    "\"define\"",
    "\"else\"",
    "\"cond\"",
    "<T_BINARY>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "<T_VARIABLE>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
  };

}
