/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package parser;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDEFINE = 2;
  public int JJTRIGHT_BRACKET = 3;
  public int JJTLEFT_BRACKET = 4;
  public int JJTVARIABLE = 5;
  public int JJTARGUMENT = 6;
  public int JJTFUNCTION = 7;
  public int JJTBOOLEAN = 8;
  public int JJTINTEGER = 9;
  public int JJTCONDITION = 10;
  public int JJTELSE = 11;


  public String[] jjtNodeName = {
    "PROGRAM",
    "void",
    "DEFINE",
    "RIGHT_BRACKET",
    "LEFT_BRACKET",
    "VARIABLE",
    "ARGUMENT",
    "FUNCTION",
    "BOOLEAN",
    "INTEGER",
    "CONDITION",
    "ELSE",
  };
}
/* JavaCC - OriginalChecksum=abf0ef00ed2d6795768698a08825917f (do not edit this line) */
